### ISSUE TITLE
Dropdowns module causing horizontal scrolling

### ISSUE THREAD

**Issue by sebnitu** [sebnitu/BaseWeb#16]
Dropdowns currently cause issues with horizontal scrolling. This happens specifically when a dropdown (even when hidden) go beyond the document window.

Possible solutions
* Could be fixed by using `display:none` when dropdowns are in hidden state
* Remove animation styles from dropdowns. Animations should be added separately from a single component.

**Comment by sebnitu** [comment]
Just used an interesting solution for this when disabling dropdown animation. If we set animations to `none` or `null`, we should just use the `display: none` and `display: block` styles instead of visibility and opacity. 

e.g:

```scss
@if (map-get($o, 'transition') == none || map-get($o, 'transition') == null) {
      display: none;
    } @else {
      opacity: 0;
      visibility: hidden;
      @include transition(map-get($o, 'transition'));
      @include transition-duration(map-get($o, 'transition-out-duration'));
      @include transition-timing-function(map-get($o, 'transition-out-timing-function'));
      @include transition-delay(map-get($o, 'transition-out-delay'));
    }
```
