### ISSUE TITLE
Make variables and component variable maps easier to override

### ISSUE THREAD

**Issue by sebnitu** [sebnitu/BaseWeb#22]
I'm playing with an idea to make variables and components more easily overridden using the custom directory and a `_overrides.scss` file. This would be loaded after settings and core files in our router and would settings here would be merged with maps in their respective component files. Example:

```scss
// @_override.scss
$overrides: (

  // Block Overrides
  'button-groups' : (),
  'notices' : (),
  'breadcrumbs' : (),
  'dropdowns' : (
    'font-size' : px-to-rem(14px),
    'border-inner' : null,
  ),
  'tabs' : ()

);

// @_some-component.scss (After the $some-component map)
// Merge some-component defaults with overrides
$some-component: map-merge($some-component, map-get($overrides, 'some-component'));
```

**Comment by sebnitu** [comment]
Also important to note, some map merging will need to use the `map-extend` function with recursive mode enabled:

```scss
$some-component: map-extend($some-component, map-get($overrides, 'some-component'), true);
```

**Comment by sebnitu** [comment]
This is what I finally settled on:

```scss
// Extend default component map with overrides if they exist
@if variable-exists(override) {
  @if (map-has-key($override, 'tabs') == true) {
    $tabs: map-extend($tabs, map-get($override, 'tabs'), true);
  }
}
```

And then, in our `_overrides.scss` file, we initiate our overrides map and extend all the global settings maps (grid and media):

```scss
$override: ();

@if variable-exists(override) {
  @if (map-has-key($override, 'grid') == true) {
    $grid: map-extend($grid, map-get($override, 'grid'), true);
  }
  @if (map-has-key($override, 'mini-grid') == true) {
    $mini-grid: map-extend($mini-grid, map-get($override, 'mini-grid'), true);
  }
  @if (map-has-key($override, 'breakpoints') == true) {
    $breakpoints: map-extend($breakpoints, map-get($override, 'breakpoints'), true);
  }
}
```
