### ISSUE TITLE
Add icon component styles

### ISSUE THREAD

**Issue by sebnitu** [sebnitu/BaseWeb#46]
I've decided we're going to use the SVG Defs styles as default icon styles for BaseWeb icons. The base styles should look like this:

```scss
.icon {
  display: inline-block;
  width: 1em;
  height: 1em;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
  font-size: 32px;
}
```

Should also include some simple SVG icons to start with and create docs for their use.
